#!/bin/bash

echo "===  _____  ＺｓｓＷｅｂ Ｖ１．０_____==="
read -p "Enter target IP or domain: " target

if [[ -z "$target" ]]; then
    echo "You must enter an IP or domain!"
    exit 1
 
paths=(
    "/"
    "/admin"
    "/admin/"
    "/administrator"
    "/administrator/"
    "/wp-admin"
    "/wp-admin/"
    "/wp-login.php"
    "/wp-content"
    "/wp-content/"
    "/wp-includes"
    "/phpmyadmin"
    "/phpmyadmin/"
    "/pma"
    "/pma/"
    "/mysql"
    "/mysql/"
    "/db"
    "/db/"
    "/adminer.php"
    "/install"
    "/install/"
    "/install.php"
    "/setup"
    "/setup/"
    "/config"
    "/config/"
    "/config.php"
    "/cpanel"
    "/cpanel/"
    "/webmail"
    "/webmail/"
    "/panel"
    "/panel/"
    "/login"
    "/login/"
    "/signup"
    "/signup/"
    "/register"
    "/register/"
    "/user"
    "/user/"
    "/users"
    "/users/"
    "/dashboard"
    "/dashboard/"
    "/controlpanel"
    "/cp"
    "/cp/"
    "/manager"
    "/manager/"
    "/backend"
    "/backend/"
    "/admincp"
    "/admincp/"
    "/adm"
    "/adm/"
    "/moderator"
    "/moderator/"
    "/bb-admin"
    "/bb-admin/"
    "/forumadmin"
    "/forumadmin/"
    "/acp"
    "/acp/"
    "/siteadmin"
    "/siteadmin/"
    "/sysadmin"
    "/sysadmin/"
    "/superadmin"
    "/superadmin/"
    "/directadmin"
    "/directadmin/"
    "/plesk"
    "/plesk/"
    "/vhost"
    "/vhost/"
    "/server-status"
    "/server-info"
    "/xmlrpc.php"
    "/.env"
    "/.git/config"
    "/robots.txt"
    "/sitemap.xml"
    "/crossdomain.xml"
    "/info.php"
    "/phpinfo.php"
    "/test.php"
    "/shell.php"
    "/cmd.php"
    "/exec.php"
    "/upload"
    "/upload/"
    "/uploads"
    "/uploads/"
    "/files"
    "/files/"
    "/filemanager"
    "/filemanager/"
    "/backup"
    "/backup/"
    "/.htaccess"
    "/wp-json"
    "/api"
    "/api/"
    "/api/v1"
    "/api/v2"
    "/graphql"
)

echo ""
echo "============================================"
echo "Target: $target"
echo "Total requests: ${#paths[@]}"
echo "============================================"
echo ""

count=1
for path in "${paths[@]}"; do
    url="http://${target}${path}"
    response_code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "$url" 2>/dev/null)
    
    if [[ "$response_code" != "000" ]]; then
        echo "[$count] $url -> Status: $response_code"
    else
        echo "[$count] $url -> No response / Timeout"
    fi
    
    count=$((count + 1))
done

echo ""
echo "============================================"
echo "Done! Checked all 100 paths."
echo "============================================"
